### ISSUE TITLE
KDDCUP dataset -regarding

### ISSUE THREAD

**Issue by Sunrup** [vinayakumarr/Network-Intrusion-Detection#6]
The code doesnt work for my kdd cup data. can you please share the data you are using. 
  " traindata = pd.read_csv('kdd/kddtrain.csv', header=None)   
testdata = pd.read_csv('kdd/kddtest.csv', header=None)"
 Is this the format and the file that we download from the site or is it preprocessed???

**Comment by alawii84** [comment]
The code doesnt work for my kdd cup data. can you please share the data you are using.
" traindata = pd.read_csv('kdd/kddtrain.csv', header=None)
testdata = pd.read_csv('kdd/kddtest.csv', header=None)"
Is this the format and the file that we download from the site or is it preprocessed???

**Comment by vinayakumarr** [comment]
you can use preprocessing step to convert the data set into numerical format

**Comment by alawii84** [comment]
Can you please provide the code you have used for encoding the dataset.

**Comment by kosnet2** [comment]
Hello Mr. vinayakumarr.

Would you mind sharing the preprocessed datasets so that I can continue my study on them ?
Thank you very much for your time and kudos for the work done on this repo.

Also, I have already converted the symbolic categorical data into numeric categorical data, but still I am running on inconsistencies.
Note that the dataset I am using is :
http://kdd.ics.uci.edu/databases/kddcup99/kddcup99.html

Should I be using sth else ?

**Comment by vinayakumarr** [comment]
Yes.

**Comment by satyarthaprakash** [comment]
> you can use preprocessing step to convert the data set into numerical format

vinayakumarr can you share the preprocessed dataset with me. I require them urgently.That would be really kind of you. thankyou

**Comment by vinayakumarr** [comment]
The datasets are publically avilable and these are standard datasets used for network intrusion detection.
